# Redirect from the default Netlify site to my custom domain
[[redirects]]
  from = "https://troyvassalotti.netlify.com/*"
  to = "https://www.troyv.dev/:splat"
  status = 301
  force = true

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1"
#    Content-Security-Policy = "default-src 'self' data: 'unsafe-inline' https://www.troyv.dev/ https://d33wubrfki0l68.cloudfront.net https://img.youtube.com/ https://www.youtube-nocookie.com/ https://bandcamp.com/ https://fonts.typotheque.com https://s3.amazonaws.com/fonts.typotheque.com/ https://cdn.skypack.dev/; worker-src blob:"
