# Build the site
[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

# Assign all the post-processing
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Redirect from the default Netlify site to my custom domain
[[redirects]]
  from = "https://troyvassalotti.netlify.com/*"
  to = "https://www.troyv.dev/:splat"
  status = 301
  force = true

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1"
    Content-Security-Policy = "default-src 'self' https://www.troyv.dev/ https://d33wubrfki0l68.cloudfront.net https://img.youtube.com/ https://www.youtube-nocookie.com/ https://fonts.typotheque.com https://unpkg.com/ https://s3.amazonaws.com/fonts.typotheque.com/ data: 'unsafe-inline'"
