---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - projects
- type: directory
  path: src/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - blog-post
upload_dir: src/assets/img
public_path: "/assets/img"
front_matter_path: "./src/assets/img"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
