# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        url: ['https://www.frontroyalband.com', 'https://pang.netlify.app', 'https://www.abandoned.website']
        name: [frorosite, pangsite, abandonedwebsite]
    runs-on: ubuntu-latest

    steps:

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: ${{ matrix.url }}
        destination: /images/screenshot-${{ matrix.name }}.png
